config/routes.rb
Rails.application.routes.draw do
  resources :cvuploads
  devise_for :users

  get '/profile', to: 'profile#index'
  get '/cvuploads', to: 'cvuploads#index'
  get '/sollicitations', to: 'sollicitations#index'
  get 'accountsettings', to: 'accountsettings#index'

  get '/accountsettings', to: 'profile#accountsettings'
  get '/', to: 'static#home'

  get '/search' => 'pages#search', :as => 'search_page'

  get '/about', to: 'static#about'
  
  get '/jobs', to: 'jobs#index'
  

  post "/apply", to: "jobs#apply"
  post "/likeCompany", to: "jobs#likeCompany"
  

  get '/portfolios', to: 'portfolios#index'

  root to: "static#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :jobs 
  resources :searches
  resources :entreprises
  # resources :portfolios
  resources :portfolios

end

app/models/adresse.rb
class Adresse < ActiveRecord::Base
    has_many :jobs
end

app/models/contracttype.rb
class Contracttype < ActiveRecord::Base
    has_many :jobs
end

app/models/cvupload.rb
class Cvupload < ActiveRecord::Base
    mount_uploader :text, AvatarUploader
end

app/models/entreprise.rb
class Entreprise < ActiveRecord::Base
   has_many :jobs
end

app/models/entrepriseadress.rb
class Entrepriseadress < ActiveRecord::Base

end

app/models/experience.rb
class Experience < ActiveRecord::Base
    has_many :jobs
end

app/models/favouritejob.rb
class Favouritejob < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base	
    belongs_to :entreprise
    belongs_to :experience
    belongs_to :adresse
    belongs_to :contracttype


    def self.search(search)
        if search
            where(["name LIKE ?","%#{search}%"])
        else
            all
        end
    end

    def self.ransackable_attributes(auth_object = nil)

    end
end

app/models/jobapplied.rb
class Jobapplied < ActiveRecord::Base
end

app/models/jobsector.rb
class Jobsector < ActiveRecord::Base
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
    has_one_attached :image, :dependent => :destroy
    has_many :personallinks
    serialize :metadata, Array

     
   before_save do
    self.strength.gsub!(/[\[\]\"]/, "") if attribute_present?("strength")
   end
 
end

app/models/search.rb
class Search < ActiveRecord::Base

    def search_jobs


        jobs = jobs.find(["name LIKE ?","‰#{keywords}"]) if keywords.present?

        return jobs
    end
    
end

app/models/sector.rb
class Sector < ActiveRecord::Base
end

app/models/socialcontact.rb
class Socialcontact < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :login
  has_one_attached :image
  has_one_attached :portfolios
  has_one_attached :personallinks

  validates :username, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A[a-zA-Z0-9 _\.]*\z/}
  validates :birthdate, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first
    else
      where(conditions.to_hash).first
  end
end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    protect_from_forgery with: :null_session #avoid the need to have a token
    before_action 
    def index
       # @jobs = Job.all 
       cookies[:message_exists] = false

       @q = Job.ransack(params[:q])
       @jobs = @q.result
       .joins(:entreprise)
       .joins(:adresse)
       .joins(:experience)
       .joins(:contracttype)

       @countJob = @jobs.size

       @entreprises = Entreprise.all
    end

    def show
        @job = Job.find(params[:id])
        # entreprise
        @entreprise = Entreprise.find(@job.entreprise_id)
        # adresse
        @adresse = Adresse.find(@job.adresse_id)
        # experience
        @experiences = Experience.find(@job.experience_id)
        # contract type
        @contractType = Contracttype.find(@job.contracttype_id) 

    end

    def create
        job = Job.create(name: 'test Name', expectations: 'expec test', description: 'desc test')
    end

    def update
        job = Job.find(params[:id])
        job.update(name: 'name upadted for id 1')
    end

    def destroy
        job = Job.find(params[:id])
        job.destroy
    end

    def apply
        job = Job.find(params[:id])
        user = current_user
        
        alreadyApplied = Jobapplied.where(
            job_id: job.id, 
            user_id: user.id
        )

        if alreadyApplied.exists? 
            cookies[:message_exists] = true
        else
            #puts job.name
            #puts user.username
            jobapplied = Jobapplied.create(
                dateAdded: DateTime.now, 
                job_id: job.id, 
                user_id: user.id)
            #puts jobapplied.job_id
            jobapplied.save 
        end
    end 

    def likeCompany
        company = Job.find(params[:id]).entreprise
        user = current_user
        alreadyLiked = Favouriteentreprise.where(
            user_id: user.id,
            entreprise_id: company.id
        )
        if alreadyLiked.exists?
            cookies[:message_exists] = true 
            redirect_back(fallback_location: root_path)
        else
            likedCompany = Favouriteentreprise.new(
                dateAdded: DateTime.now,  
                user_id: user.id,
                entreprise_id: company.id
            )
            
           likedCompany.save
        end 
    end

end

app/helpers/cvuploads_helper.rb
module CvuploadsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

    def checked(area)
        @portfolio.strength.nil? ?  false : @portfolio.strength.match(area)
    end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/index.html.erb
<div class="text-base font-medium text-teal-600 py-2 px-4 rounded">
    <h1 class='font-black text-6xl text-center'>Jobs</h1>
</div>
<!--
    Using ransack gem for the filter. 

    Filtre:
        * Code postal                                   DONE
        * Max distance
    Entreprise
        Qiwie, Aubay ....                               DONE   
    Experience
        Junior, Medior, Senior                          DONE
    Type de contrat
        Partiel time, half time, full time              DONE
    Technologies
        Javascript, Python, Ruby, C#, Java, ...         DONE
-->


<aside class="float-left w-60 p-8 bg-teal-700 m-1">
    <div class="text-xs font-light text-teal-200"><%= @countJob %> jobs found.</div>
   <%= search_form_for @q do |j|%>
        <h4 class="text-2xl text-teal-200">Filtre</h4>
        <div class="text-lg text-teal-400">

            <!--
                  /!\ the lines j.search... throw the error "undefined method `include?' for nil:NilClass"
                  no idea why.

                  I remove those lines and put it here to be able to display the page for now:

                  j.collection_select :contracttype_id_eq, Contracttype.all, :id, :name, include_blank: true
                  j.search_field :entreprise_name_cont
                  j.collection_select :experience_id_eq, Experience.all, :id, :name, include_blank: true
                  j.search_field :name_cont

            -->
            <%= fa_icon "file-alt" %>
            <%= j.label :contracttype_name_cont_not_null, 'Contract type?'%>

            <br/>
            <%= fa_icon "building" %>
            <%= j.label :entreprise_name_cont, 'Entreprise?'%>

            <br/>
            <%= fa_icon "laptop" %>
            <%= j.label :experience_id_eq, 'Experience' %>
            <br/>

            <%= fa_icon "cogs" %>
            <%= j.label :name_cont, 'Technology?' %>
        </div>

        <br/>
        <div class="bg-teal-900 py-2 px-4 rounded-md hover:bg-teal-400"><%=j.submit %></div>
    <% end %>
</aside>

<% @jobs.each do |job|%>
    <div class="bg-teal-700 rounded-lg shadow-lg mt-8 w-2/5 mx-auto">
    <div class="flex flex-row justify-center">
        <p class="font-black text-2xl text-center"> <%= job.entreprise.name %></p>
         <%=  button_to(action: "likeCompany", id: job.id) do%>
            <%= fa_icon "heart", class: "" %>
         <% end %>
    </div>
        <div  class="flex justify-around flex-wrap font-black text-1xl text-center"> 
            <a class="bg-teal-400 py-2 px-4 border border-transparent 
            rounded-md text-base font-medium text-white hover:bg-teal-300 mb-6" 
            href="<%= job_path(job.id)%>">
             <%= job.name %>
            </a>
        </div>
    </div>
<% end %>

<br/><br/><br/>
<div class="text-base font-medium text-teal-600 py-2 px-4 rounded pb-6">
    <h1 class='font-black text-6xl text-center'>Companies</h1>
</div>
<div class="flex flex-row justify-center gap-4 flex-wrap">
    <% @entreprises.each do |e|%>
        <div class="m-4 bg-teal-700 rounded-lg shadow-lg w-2/12 h-48 font-black text-2xl text-center">
            <%= e.name %>
            <%= image_tag "/logoEntreprise/"+ e.logo, style: 'display: block; margin-left: auto; margin-right: auto; width: 50%;' %>
        </div>
    <% end %>
</div>



app/views/jobs/show.html.erb
<div class="mx-16">
    <dl class="text-left w-full bg-teal-700 pr-4">
        <dd class="text-center text-2xl font-semibold text-teal-400"><%= @job.name %></dd>  
        <% if current_user %>        
            <dd class= "float-right"><%= button_to 'Apply', :action => "apply", id: @job.id, form_class: "w-12 h-4 bg-red-500" %></dd>                           
        <% end %>
        <dd class="text-teal-200 pl-4">Location: <%= @adresse.street + ", " + @adresse.city + ", " + @adresse.country %></dd> 
        <div class="flex flex-row justify-between">
            <dd class="text-teal-200 pl-4">Entreprise: <%= @entreprise.name %></dd> 
            <%=  button_to(action: "likeCompany", id: @job.id) do%>
              <div class="text-green-600"> Like this company <%= fa_icon "heart", class: "text-red-600 " %> </div>
            <% end %>
        </div>
        
        <dd class="text-teal-200 pl-4">Contract type: <%= @contractType.name %></dd>
        <dd class="text-teal-200 pl-4">Experience: <%= @experiences.name %></dd>
        <% unless @job.dateAdded.nil? %>
            <dd class="text-teal-200 pl-4">Date added: <%= @job.dateAdded %></dd>
        <% end %>
    </dl>
    
    <div>
        <h2 class="text-xl font-medium text-teal-400">Job description</h2>
        <p><%= @job.description %></p>
        <h2 class="text-xl font-medium text-teal-400">Job expectations</h2>
        <p><%= @job.expectations %></p>
    </div>
    <%= link_to "Back", :back %>
</div>
