config/routes.rb
Rails.application.routes.draw do
  resources :cvuploads
  devise_for :users

  get '/profile', to: 'profile#index'
  get '/cvuploads', to: 'cvuploads#index'
  get '/sollicitations', to: 'sollicitations#index'
  get 'accountsettings', to: 'accountsettings#index'

  get '/accountsettings', to: 'profile#accountsettings'
  get '/', to: 'static#home'

  get '/search' => 'pages#search', :as => 'search_page'

  get '/about', to: 'static#about'
  
  get '/jobs', to: 'jobs#index'
  

  post "/apply", to: "jobs#apply"
  post "/likeCompany", to: "jobs#likeCompany"
  

  get '/portfolios', to: 'portfolios#index'

  root to: "static#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :jobs 
  resources :searches
  resources :entreprises
  # resources :portfolios
  resources :portfolios

end

app/models/adresse.rb
class Adresse < ActiveRecord::Base
    has_many :jobs
end

app/models/contracttype.rb
class Contracttype < ActiveRecord::Base
    has_many :jobs
end

app/models/cvupload.rb
class Cvupload < ActiveRecord::Base
    mount_uploader :text, AvatarUploader
end

app/models/entreprise.rb
class Entreprise < ActiveRecord::Base
   has_many :jobs
end

app/models/entrepriseadress.rb
class Entrepriseadress < ActiveRecord::Base

end

app/models/experience.rb
class Experience < ActiveRecord::Base
    has_many :jobs
end

app/models/favouritejob.rb
class Favouritejob < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base	
    belongs_to :entreprise
    belongs_to :experience
    belongs_to :adresse
    belongs_to :contracttype


    def self.search(search)
        if search
            where(["name LIKE ?","%#{search}%"])
        else
            all
        end
    end

    def self.ransackable_attributes(auth_object = nil)

    end
end

app/models/jobapplied.rb
class Jobapplied < ActiveRecord::Base
end

app/models/jobsector.rb
class Jobsector < ActiveRecord::Base
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
    has_one_attached :image, :dependent => :destroy
    has_many :personallinks
    serialize :metadata, Array

     
   before_save do
    self.strength.gsub!(/[\[\]\"]/, "") if attribute_present?("strength")
   end
 
end

app/models/search.rb
class Search < ActiveRecord::Base

    def search_jobs


        jobs = jobs.find(["name LIKE ?","‰#{keywords}"]) if keywords.present?

        return jobs
    end
    
end

app/models/sector.rb
class Sector < ActiveRecord::Base
end

app/models/socialcontact.rb
class Socialcontact < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :login
  has_one_attached :image
  has_one_attached :portfolios
  has_one_attached :personallinks

  validates :username, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A[a-zA-Z0-9 _\.]*\z/}
  validates :birthdate, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first
    else
      where(conditions.to_hash).first
  end
end
end

app/controllers/cvuploads_controller.rb
class CvuploadsController < ApplicationController
  before_action :set_cvupload, only: %i[ show edit update destroy ]

  # GET /cvuploads or /cvuploads.json
  def index
    @cvuploads = Cvupload.all
  end

  # GET /cvuploads/1 or /cvuploads/1.json
  def show
  end

  # GET /cvuploads/new
  def new
    @cvupload = Cvupload.new
  end

  # GET /cvuploads/1/edit
  def edit
  end

  # POST /cvuploads or /cvuploads.json
  def create
    @cvupload = Cvupload.new(cvupload_params)

    respond_to do |format|
      if @cvupload.save
        format.html { redirect_to @cvupload, notice: "Cvupload was successfully created." }
        format.json { render :show, status: :created, location: @cvupload }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cvupload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cvuploads/1 or /cvuploads/1.json
  def update
    respond_to do |format|
      if @cvupload.update(cvupload_params)
        format.html { redirect_to @cvupload, notice: "Cvupload was successfully updated." }
        format.json { render :show, status: :ok, location: @cvupload }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cvupload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cvuploads/1 or /cvuploads/1.json
  def destroy
    @cvupload.destroy
    respond_to do |format|
      format.html { redirect_to cvuploads_url, notice: "Cvupload was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cvupload
      @cvupload = Cvupload.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cvupload_params
      params.require(:cvupload).permit(:text)
    end
end

app/helpers/cvuploads_helper.rb
module CvuploadsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

    def checked(area)
        @portfolio.strength.nil? ?  false : @portfolio.strength.match(area)
    end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/user_steps_helper.rb
module UserStepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cvuploads/_form.html.erb
<%= form_with(model: cvupload) do |form| %>
  <% if cvupload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cvupload.errors.count, "error") %> prohibited this cvupload from being saved:</h2>

      <ul>
        <% cvupload.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.file_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cvuploads/edit.html.erb

<div class="bg-gray-50 h-screen w-screen">
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>

        <div class=" bg-gray-50 w-4/5  mt-10 mx-auto text-center space-x-6 p-10">
                <button class="bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Profile', 'profile' %></button>
                <button class="bg-green-500 m-2 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Upload CV', 'cvuploads' %></button>
                <button class="bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Sollicitations', 'sollicitations' %></button>
                <button class="bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Account Settings', 'accountsettings' %></button>
        </div>
       
        

<div class="bg-blue-100 w-4/5 mx-auto text-center">
        
        <h1 class='font-black text-4xl text-center'>Upload a CV<h1>


<%= render 'form', cvupload: @cvupload %>

<%= link_to 'Show', @cvupload %> |
<%= link_to 'Back', cvuploads_path %>


</div>
</div>

app/views/cvuploads/index.html.erb

<div class="bg-gray-50 h-screen w-screen">
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>

        <div class=" bg-gray-50 w-4/5  mt-10 mx-auto text-center space-x-6 p-10">
                <button class="bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Profile', 'profile' %></button>
                <button class="bg-green-500 m-2 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Upload CV', 'cvuploads' %></button>
                <button class="bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Sollicitations', 'sollicitations' %></button>
                <button class="bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Account Settings', 'accountsettings' %></button>
        </div>
       
        

<div class="bg-blue-100 w-4/5 mx-auto text-center">
        
        <h1 class='font-black text-4xl text-center'>Upload a CV<h1>

  <tbody>

    <% @cvuploads.each do |cvupload| %>
      <tr>
        <td><%= cvupload.text %></td>
        <td><%= link_to 'Show', cvupload %></td>
        <td><%= link_to 'Edit', edit_cvupload_path(cvupload) %></td>
        <td><%= link_to 'Destroy', cvupload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cvupload', new_cvupload_path %>

</div>
</div>

app/views/cvuploads/new.html.erb

<div class="bg-gray-50 h-screen w-screen">
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>

        <div class=" bg-gray-50 w-4/5  mt-10 mx-auto text-center space-x-6 p-10">
                <button class="bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Profile', 'profile' %></button>
                <button class="bg-green-500 m-2 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Upload CV', 'cvuploads' %></button>
                <button class="bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Sollicitations', 'sollicitations' %></button>
                <button class="bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Account Settings', 'accountsettings' %></button>
        </div>
       
        

<div class="bg-blue-100 w-4/5 mx-auto text-center">
        
        <h1 class='font-black text-4xl text-center'>Upload a CV<h1>

<%= render 'form', cvupload: @cvupload %>

<%= link_to 'Back', cvuploads_path %>

</div>
</div>

app/views/cvuploads/show.html.erb

<div class="bg-gray-50 h-screen w-screen">
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>

        <div class=" bg-gray-50 w-4/5  mt-10 mx-auto text-center space-x-6 p-10">
                <button class="bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Profile', 'profile' %></button>
                <button class="bg-green-500 m-2 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Upload CV', 'cvuploads' %></button>
                <button class="bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Sollicitations', 'sollicitations' %></button>
                <button class="bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"><%= link_to 'Account Settings', 'accountsettings' %></button>
        </div>
       
        

<div class="bg-blue-100 w-4/5 mx-auto text-center">
        
        <h1 class='font-black text-4xl text-center'>Upload a CV<h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @cvupload.text %>
</p>

<%= link_to 'Edit', edit_cvupload_path(@cvupload) %> |
<%= link_to 'Back', cvuploads_path %>


</div>
</div>